#!/usr/bin/env python

import os
import sys
import time
import signal
import struct
import random


def stop(*a, **kw):
    sys.exit(0)

signal.signal(signal.SIGINT, stop)
signal.signal(signal.SIGTERM, stop)

time.sleep(3)

sys.stdout.write("READY")
sys.stdout.flush()


while True:
    length, = struct.unpack('L', sys.stdin.read(4))
    message = sys.stdin.read(length)
    message = message*3
    sys.stdout.write(struct.pack('L', len(message))+message)
    sys.stdout.flush()
